name: Build matlab bindings
on: [push,pull_request]
jobs:
  build:
    name: Build and Test Solverdummies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - release: latest
        - release: R2021b
        - release: R2021a
        - release: R2020b
        - release: R2020a
    steps:
      - name: Install precice
        run: |
          wget https://github.com/precice/precice/releases/download/v2.4.0/libprecice2_2.4.0_focal.deb 
          sudo apt install ./libprecice2_2.4.0_focal.deb

      # - name: upload file artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: precice-package
      #     path: libprecice2_2.4.0_bullseye.deb

      - name: Fix `version 'GLIBCXX_3.4.26' not found`
        run: |
          echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6' >> ~/.bashrc
          source ~/.bashrc

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with: 
          release: ${{ matrix.release }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run compilation script
        uses: matlab-actions/run-command@v1
        with:
          command: compile_matlab_bindings_for_precice
  
      - name: Run Solverdummies
        run: |
          matlab -sd "./solverdummy" -batch "addpath('../'); solverdummy precice-config.xml SolverOne;" & matlab -sd "./solverdummy" -batch "addpath('../'); solverdummy precice-config.xml SolverTwo;"

