name: 'Test Matlab bindings'

on: [push,pull_request]
jobs:
  test-solverdummies:
    name: Test matlab solverdummmies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - release: latest
        - release: R2021b
        - release: R2021a
        - release: R2020b
        - release: R2020a
    steps:
      - name: setup matlab bindings
        uses: precice/matlab-bindings/build@v1
        with:
          matlab-release: ${{ matrix.release }}
          precice-version: '2.4.0'

      - name: Run Solverdummies
        run: |
          LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab -sd "./solverdummy" -batch "addpath('../'); solverdummy precice-config.xml SolverOne;" & LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab -sd "./solverdummy" -batch "addpath('../'); solverdummy precice-config.xml SolverTwo;"
  
  test-tutorial:
    name: Test matlab solverdummmies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - release: latest
        - release: R2021b
        - release: R2021a
        - release: R2020b
        - release: R2020a
    steps:
      - name: setup matlab bindings
        uses: precice/matlab-bindings/build@v1
        with:
          matlab-release: ${{ matrix.release }}
          precice-version: '2.4.0'

      - name: Run Tutorials
        run: |
          LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab -sd "./tutorial/implicit" -batch "addpath('../../'); Solver_I;" & LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 matlab -sd "./tutorial/implicit" -batch "addpath('../../'); Solver_U;"

